### ISSUE TITLE
No demo?

### ISSUE THREAD

**Issue by heyallan** [leotrieu/Code4Startup.Ninja#3]
Why no live demo?

**Comment by leotrieu** [comment]
I've already provided open source so haven't thought about that. But it's good point to think.

**Comment by leotrieu** [comment]
@fuczak What do you think?

**Comment by heyallan** [comment]
Demo helps to compare progress, visualize behavior, etc. Mostly for visual people.
Also, tangible demonstration is motivational.

**Comment by fuczak** [comment]
@heyallan Do you mean a live website for each stage of building the app (after each task)? I don't think that's necessary - every step is explained in it's first video, you can see the functionality that's going to be added. There is nothing going behind the scenes so if you follow the tutorial closely you are going to end up with exactly the same product at each stage.

If you mean a website for finished app - that's a good idea. Actuallly, I'm surprised that https://task-ninja.firebaseapp.com/ doesn't work. @leotrieu That shouldn't be too hard to fix. There are some problems with HTTP requests being blocked.

In the meantime you can use https://task-fu.firebaseapp.com/

**Comment by heyallan** [comment]
`https://task-ninja.firebaseapp.com` is exactly what I meant.
I suggest adding the link to `README.md` if possible.

Thanks.

**Comment by leotrieu** [comment]
Done, you can check it here: https://task-ninja.firebaseapp.com

**Comment by heyallan** [comment]
<3
