### ISSUE TITLE
User object vs. profile object

### ISSUE THREAD

**Issue by heyallan** [leotrieu/Code4Startup.Ninja#4]
In `scripts/services/auth.js:13~` what's the difference between `user {}` and `profile {}` objects?
I get the impression that you could have accesed `user {}` data directly.

**Comment by fuczak** [comment]
From https://www.firebase.com/docs/web/guide/user-auth.html

> It does not store profile or user state in your Firebase. To persist user data you must save it to your Firebase.

**Comment by leotrieu** [comment]
In `scripts/services/auth.js`, in the auth.$onAuth(...), notice how we assign value to user {} and profile {}:

``` ruby
angular.copy(authData, Auth.user);
Auth.user.profile = $firebase(ref.child('profile').child(authData.uid)).$asObject();
```

**Comment by heyallan** [comment]
If I understand correctly:
- `user {}` is the object returned by `$authWithPassword()` initially
- `profile {}` is the object returned by reading `$(firebase(ref.child())` afterwards

**Comment by leotrieu** [comment]
You're on the right track now.
