### ISSUE TITLE
ChangePassword doesnt work

### ISSUE THREAD

**Issue by ninoCookies** [leotrieu/Code4Startup.Ninja#8]
Change password does not work. 

error:
ReferenceError: email is not defined

**Comment by leotrieu** [comment]
Can you show me your git repo?

**Comment by ninoCookies** [comment]
I just downloaded and locally hosted TaskNinja-T8 from your repo.

**Comment by leotrieu** [comment]
Looks like it doesn't. I'll have a look at this issue. Thanks for letting me know that!

**Comment by leotrieu** [comment]
@freeman128 It should be good now. Let me know if you still have the issue.
